[tool.black]
line-length = 100
target-version = ["py310", "py311", "py312", "py313"]
# Ignore vendored/research and non-source directories
extend-exclude = """
(
  ^src/core/metrics/civai_bias/FlagEmbedding
| ^src/core/metrics/civai_bias/CivoraAI
| ^src/core/metrics/civai_bias/data
| ^src/core/metrics/civai_bias/notebooks
| ^src/core/metrics/civai_bias/outputs
| ^src/core/metrics/civai_bias/tests
| ^src/core/metrics/civai_bias/.vscode
| ^scripts
| ^docs
)
"""

[tool.ruff]
line-length = 100
target-version = "py310"

[tool.ruff.lint]
# Sort imports, basic hygiene
extend-select = ["I"]

# Exclude vendored/research and non-source directories
extend-exclude = [
  "src/core/metrics/civai_bias/FlagEmbedding",
  "src/core/metrics/civai_bias/CivoraAI",
  "src/core/metrics/civai_bias/data",
  "src/core/metrics/civai_bias/notebooks",
  "src/core/metrics/civai_bias/outputs",
  "src/core/metrics/civai_bias/tests",
  "src/core/metrics/civai_bias/.vscode",
  "src/core/metrics/civai_bias/**/setup.py",
  "scripts/**",
  "docs/**",
  "tests/**/__pycache__",
]

[tool.ruff.lint.per-file-ignores]
"**/__init__.py" = ["F401"]