name: CI

on:
  push:
    branches: [ main, "**" ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Ensure dev tools present in CI even if not pinned yet
          pip install black ruff pytest httpx

      - name: Black (check only)
        run: black --check .

      - name: Ruff (lint)
        run: ruff check .

      - name: Pytest
        env:
          # Example envs if code reads them; safe defaults
          APP_ENV: test
          APP_PORT: 8000
          ALLOW_ORIGINS: http://localhost:5173
        run: pytest -q
