name: CI

on:
  push:
    branches: [ main, "**" ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    env:
      # Make `from src...` imports work during pytest
      PYTHONPATH: .
      # Safe defaults if app reads envs
      APP_ENV: test
      APP_PORT: 8000
      ALLOW_ORIGINS: http://localhost:5173

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Show Python & pip
        run: |
          python --version
          pip --version

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Ensure dev tools present even if not pinned yet
          pip install black ruff pytest httpx

      - name: Black (check only)
        run: black --check src/api src/services src/utils tests src/core/metrics/simple_score.py

      - name: Ruff (lint)
        run: ruff check .

      - name: Pytest
        run: pytest -q -rA